//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudyDec2016.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchProject", ReplyAction="http://tempuri.org/IService1/searchProjectResponse")]
        System.Data.DataSet searchProject(string pname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchCategory", ReplyAction="http://tempuri.org/IService1/searchCategoryResponse")]
        System.Data.DataSet searchCategory(string cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchEmp", ReplyAction="http://tempuri.org/IService1/SearchEmpResponse")]
        System.Data.DataSet SearchEmp(string f, string l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchskill", ReplyAction="http://tempuri.org/IService1/searchskillResponse")]
        System.Data.DataSet searchskill(string fname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CaseStudyDec2016.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CaseStudyDec2016.ServiceReference1.IService1>, CaseStudyDec2016.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet searchProject(string pname) {
            return base.Channel.searchProject(pname);
        }
        
        public System.Data.DataSet searchCategory(string cat) {
            return base.Channel.searchCategory(cat);
        }
        
        public System.Data.DataSet SearchEmp(string f, string l) {
            return base.Channel.SearchEmp(f, l);
        }
        
        public System.Data.DataSet searchskill(string fname) {
            return base.Channel.searchskill(fname);
        }
    }
}
